# List of magazines
#   filename  : a magazine name starts with 'filename' followed by a number, eg. MagPi01, MagPi123
#   language  : available EN (English), NL (Dutch)
#   directory : the folder which contains the magazines
#   database  : the name of the database

magazines:
  magpi:
    filename: MagPi
    language: EN
    directory: /home/pi/nas/HOBBY/Magazines/MagPi/
    database: magpi.db
  hackspace:
    filename: HackSpace
    language: EN
    directory: /home/pi/nas/HOBBY/Magazines/HackSpace/
    database: hackspace.db
  elektor:
    filename: Elektor
    language: NL
    directory: /home/pi/nas/HOBBY/Magazines/Elektor/
    database: elektor.db

# Default mode of matching search terms to keys. Options are:
#   --any   : any position of the search term in the key word
#   --start : search term has to be at the start of the keyword
#   --exact : exact match between search term and keyword

match_mode: --any
